# Linear Algebra Review with Numpy

author: Ren Zhang (ryanzjlib@gmail.com)

I am using python 2.7, but i am writing in a way that hopefully it will be compatable with python 3

The purpose of this notebook is to help you get a refresher on ensenssial linear algebra with numpy

In [1]:
from __future__ import print_function
from __future__ import division

# load numpy library
import numpy as np

## Create Matrix and Vector

In [2]:
# A is a 4 by 2 matrix
A = np.array([[1,2],
              [3,4],
              [5,6],
              [7,8]])

print(A)
print(A.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4L, 2L)


In [3]:
# B is a 4 by 2 matrix
B = np.array([[8,7],[6,5],[4,3],[2,1]])

print(B)
print(B.shape)

[[8 7]
 [6 5]
 [4 3]
 [2 1]]
(4L, 2L)


In [4]:
# v is a column vector
v = np.array([2,1]).reshape(2,1)

print(v)
print(v.shape)

[[2]
 [1]]
(2L, 1L)


## Transpose

In [5]:
print(A.T)
print(A.T.shape)
print(np.transpose(A))

[[1 3 5 7]
 [2 4 6 8]]
(2L, 4L)
[[1 3 5 7]
 [2 4 6 8]]


In [6]:
print(v.T)
print(v.T.shape)
print(np.transpose(v))

[[2 1]]
(1L, 2L)
[[2 1]]


In [7]:
# the transpose of transpose is the original
print(np.transpose(np.transpose(A)))
print(A.T.T)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Calculations

In [8]:
# matrix and matrix addition, element wise
print(A + B)
print(np.add(A, B))

[[9 9]
 [9 9]
 [9 9]
 [9 9]]
[[9 9]
 [9 9]
 [9 9]
 [9 9]]


### Broadcast

In [9]:
# matrix and scalar addition, broadcasted
print(4 + A)

[[ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [10]:
# matrix and vector addition, 
# the vector is broadcasted to add to each row of matrix
# A is 4 by 2 vector is 2 by 1
print(A+v.T)

[[3 3]
 [5 5]
 [7 7]
 [9 9]]


### Multiplication  

In [11]:
# element wise matrix multiplication exists
print(A * B)

[[ 8 14]
 [18 20]
 [20 18]
 [14  8]]


## Dot Product

In [12]:
B = B.T
# dot product A.shape = m by n B.shape = n by m
print(A.shape, B.shape)
print(A.dot(B))

# note the order matters, it is not commutative
print(np.dot(B, A))

(4L, 2L) (2L, 4L)
[[ 22  16  10   4]
 [ 52  38  24  10]
 [ 82  60  38  16]
 [112  82  52  22]]
[[60 80]
 [44 60]]


In [13]:
# dot product of two vectors is a scalar
u = v.T
print(u.dot(v))

[[5]]


In [14]:
# dot product is distributive
C = np.array([[2,1],[3,4]])
D = np.array([[4,2],[1,5]])
E = np.array([[5,6],[4,4]])

print(np.dot(A, (C + D)))
print(np.add(np.dot(A, C), np.dot(A, D)))

[[14 21]
 [34 45]
 [54 69]
 [74 93]]
[[14 21]
 [34 45]
 [54 69]
 [74 93]]


In [15]:
# dot product is also associative
print(np.dot(C, np.dot(D, E)))
print(np.dot(np.dot(C,D), E))

[[ 81  90]
 [184 200]]
[[ 81  90]
 [184 200]]


In [16]:
## == Transpose of a result of dot product
# (A.B).T is equal to (B.T).(A.T)
print(np.transpose(A.dot(B)))
print(B.T.dot(A.T))

[[ 22  52  82 112]
 [ 16  38  60  82]
 [ 10  24  38  52]
 [  4  10  16  22]]
[[ 22  52  82 112]
 [ 16  38  60  82]
 [ 10  24  38  52]
 [  4  10  16  22]]


### identity matrix

In [17]:
## identity matrix, a matrix with 1 on diag and 0 else where
I = np.eye(4)
print(I)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


## Solve a linear system using linear algebra

In [18]:
## == Matrix dot vector as linear system
# Ax = b
x = np.array([2,1])
b = np.array([4, 10, 16, 22])
print(A.dot(x))

[ 4 10 16 22]


In [19]:
# each row of A dot the vector x, representing a single linear equation
for row in A:
	print(row.dot(x))

4
10
16
22


### Matrix Inversion

In [20]:
# A' is a inversion of A, if A'.T dot A = I (the identity)
# only square matrices can have strict inverse
# use pesudoinverse when matrix is not square 
from numpy.linalg import inv
from numpy.linalg import pinv
Ainv = pinv(A)
print(Ainv.dot(A))

[[  1.00000000e+00   1.33226763e-15]
 [  8.88178420e-16   1.00000000e+00]]


In [21]:
# we can solve for x using A' dot b using matrix inverse
print(Ainv.dot(b))
print(x)

[ 2.  1.]
[2 1]


### Norm

In [22]:
from numpy.linalg import norm
print(b)

# L1 norm: sum of abs values
print(norm(b, ord = 1))

# L2 norm: euclidean distance from origin
print(norm(b, ord = 2))

# max norm: the abs of the largested direction
print(norm(b, ord = np.inf))

# the Frobenius norm of a matrix
print(norm(A))
print(np.sqrt(sum(A.ravel()**2)))

[ 4 10 16 22]
52.0
29.2574776767
22.0
14.2828568571
14.2828568571


## Eigen Decomposition

decompose a square matrix into a set of eigen values and eigen vectors  
a vector v is called a eigen vector of matrix M if  
+ M dot v = lambda * v

where lambda is a scalar value also called the eigen value associated with this eigen vector v

the eigen vectors are the columns of V from numpy output

In [23]:
from numpy.linalg import eig

M = np.array([[1,2,4],[2,3,7],[8,6,3]])

# eigen decopose
lambdas, V = eig(M)
print(lambdas)
print(V)
print(M.dot(V[:,0]))
print(lambdas[0] * V[:,0])

[ 12.26352157  -0.31295623  -4.95056534]
[[-0.35906776 -0.51630781 -0.3087166 ]
 [-0.61078586  0.82168525 -0.58360762]
 [-0.70569893 -0.24137024  0.75106339]]
[-4.40343519 -7.49038559 -8.65435402]
[-4.40343519 -7.49038559 -8.65435402]


another way to look at this decomposition: 

M = V dot diag(lambdas) dot V'

which means we can reconstruct the original matrix M from a matrix V, its inverse and a diagnoal matrix diag(lambdas)

In [24]:
print(M)

print(V.dot(np.diag(lambdas)).dot(inv(V)))

[[1 2 4]
 [2 3 7]
 [8 6 3]]
[[ 1.  2.  4.]
 [ 2.  3.  7.]
 [ 8.  6.  3.]]


note not always able to do eigen decomposition on matrices

In [25]:
try:
	print(eig(A))
except:
	print("not possible")

not possible


## Singular Value Decompose

decompose a matrix A (m by n) into three components

A = U dot D dot V.T

+ U (m by m) eigen vectors of A dot A.T
+ D (m by n) only has value on diag, collected into vector s, eigen values of A dot A.T or A.T dot A
+ V (n by n) eigen vectors of A.T dot A


In [26]:
from numpy.linalg import svd

U, s, VT = svd(A)

V = VT.T
D = np.zeros((U.shape[0], V.shape[0]))
D[:s.size, :s.size] = np.diag(s)

print(U.dot(D).dot(V.T))

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]


### Moore Penrose pseudo inverse
let U, D, V be the singular value decomposition results from A  
let D+ be the pseudo inverse of D  
then A+ = V dot D+ dot U.T

the pseudo inverse of a diag matrix is simply transpose and take reciprocal    

In [27]:
print(D)
print(pinv(D))

[[ 14.2690955    0.        ]
 [  0.           0.62682823]
 [  0.           0.        ]
 [  0.           0.        ]]
[[ 0.07008153  0.          0.          0.        ]
 [ 0.          1.59533338  0.          0.        ]]


In [28]:
print(pinv(A))
print(V.dot(pinv(D)).dot(U.T))

[[ -1.00000000e+00  -5.00000000e-01   1.01307851e-15   5.00000000e-01]
 [  8.50000000e-01   4.50000000e-01   5.00000000e-02  -3.50000000e-01]]
[[ -1.00000000e+00  -5.00000000e-01   1.01307851e-15   5.00000000e-01]
 [  8.50000000e-01   4.50000000e-01   5.00000000e-02  -3.50000000e-01]]


###  Trace
trace is the sum of diagonal elemenets of a matrix   
it is useful to rewrite some formulas


In [29]:
print(np.trace(A))
print(np.sum(np.diag(A)))

5
5


In [30]:
print(np.sqrt(np.trace(A.dot(A.T))))
print(norm(A))

14.2828568571
14.2828568571


### determinant
for a square matrix, the determinant is equal to the product of all eigenvalues of a matrix.  
the abs value of determinant can be thought as a measure of how much multiplication by the matrix expands or contracts space

In [31]:
from numpy.linalg import det
print(det(M))

19.0
